---
abstract: 'convert japanese chars.'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Regular-Unicode
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 5.58
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
