---
abstract: 'convert japanese chars.'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::Base: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Regular-Unicode
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Lingua::JA::Regular::Unicode:
    file: lib/Lingua/JA/Regular/Unicode.pm
    version: 0.10
requires:
  Exporter: 5.58
  Filter::Util::Call: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
